# Generated by Django 3.1.4 on 2020-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storyshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='w_saying',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='w_saying',
            name='saying',
            field=models.CharField(max_length=50),
        ),
    ]
